<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Essa.Framework.Web</RootNamespace>
    <AssemblyName>Essa.Framework.Web</AssemblyName>
  </PropertyGroup>

  
	<ItemGroup>
    <PackageReference Include="DataTables.AspNet.AspNetCore" Version="2.0.2" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Essa.Framework.MensageriaCore\Essa.Framework.MensageriaCore.csproj" />
    <ProjectReference Include="..\Essa.Framework.UtilCore\Essa.Framework.UtilCore.csproj" />
  </ItemGroup>

</Project>
